elastic/harp

README.md
cmd/harp/internal/cmd/passphrase.go
pkg/sdk/value/encryption/aes/helpers.go
samples/act-as-vault-server/README.md

Fix OSS scanner findings and add badges.

Chore doc badges

---

.gitattributes
.github/workflows/codeql-analysis.yml
.github/workflows/golangci-lint.yml
README.md

* Add `golangci-lint` scan on push and or
* Add `lgtm` badge to readme

Chore ci gha golangci

---

docs/cso/HowTo.md

This is a document to do a "user friendly" (or "non-programmer friendly") introduction to harp, templates, and the CSO. It references the in-depth technical information, but is designed to get a person up and running with the basic concepts.

A simpler introduction document for Harp and CSO, first version

---

cmd/harp-server/go.sum
pkg/tasks/from/vault.go
pkg/tasks/to/vault.go

fix(lint): error shadowing warning after golangci update.

---

tools/go.mod

Update commit reference in go.mod.
See https://github.com/mvdan/mvdan.cc/issues/3.
Rel: https://github.com/elastic/cloud/pull/74389

[tools] go.mod update for mvdan.cc

---

.gitignore
Taskfile.yml
build/mage/golang/is.go
build/mage/release/formula.go
cmd/harp-server/Taskfile.yml
cmd/harp-server/magefile.go
magefile.go

chore(ci): rework taskfiles.

---

Taskfile.yml
cmd/harp/internal/cmd/from.go
cmd/harp/internal/cmd/from_oplog.go
pkg/bundle/codec.go
pkg/bundle/compare/diff.go
pkg/bundle/helpers.go
pkg/bundle/template/visitor/secretbuilder/api_test.go
pkg/tasks/from/oplog.go

Create a new bundle from an `oplog` output.

feat(oplog): create a bundle from oplog.

---

pkg/bundle/ruleset/bundle.go

fix(linter): apiversion for ruleset generator.

---

cmd/harp/internal/cmd/share_get.go
cmd/harp/internal/cmd/share_put.go
pkg/vault/cubbyhole/service.go

share command was initializing empty parameters that crash the CLI.

fix(share): invalid cli parameters.

---

FEATURES.md
README.md

doc(main): reorganize readme.

---

README.md

- English review
- Add more content on the immutable container principle topic

fix(lang): english review.

---

README.md

fix(doc): rewording secret management process.

---

FEATURES.md
README.md

Work on features and general presentation.

doc(features): global document rework.

---

FEATURES.md
cmd/harp/internal/cmd/keygen_aes_siv.go
pkg/sdk/value/encryption/aead/builders.go
pkg/sdk/value/encryption/transformer.go
pkg/sdk/value/encryption/transformer_test.go

Add missing feature documentation

doc(feature): reorganize feature and add missing entries.

---

samples/onboarding/1-template-engine/2-functions.md

doc(functions): update secret loader sample.

---

cmd/harp/internal/cmd/from.go
cmd/harp/internal/cmd/from_object.go
cmd/harp/internal/cmd/to_object.go
go.mod
pkg/sdk/value/flatmap/expand.go
pkg/sdk/value/flatmap/expand_test.go
pkg/tasks/from/object.go
pkg/tasks/to/object.go
samples/sops/README.md
samples/sops/production.yaml

* `harp from object` - Import a YAML/JSON structure as a secret container.
* `harp to object` - Export a secret container as a YAML/JSON structure.

feat(yaml): importer / exporter.

---

cmd/harp/internal/cmd/keygen_paseto.go
pkg/sdk/value/encryption/paseto/helpers.go
pkg/sdk/value/encryption/paseto/helpers_test.go
pkg/sdk/value/encryption/paseto/transformer.go

* Implement PASETO v4 `public` signature algorithm.
- https://github.com/paseto-standard/paseto-spec/blob/master/docs/01-Protocol-Versions/Version4.md

Feat crypto paseto v4 public

---

cmd/harp/internal/cmd/from_consul.go
cmd/harp/internal/cmd/to_consul.go
pkg/kv/consul/api.go
pkg/kv/consul/consul.go
pkg/kv/consul/consul_test.go
test/integration/kv/consul_test.go

Test kv consul unit tests

---

pkg/sdk/security/crypto/paseto/v4/helpers.go
pkg/sdk/security/crypto/paseto/v4/helpers_test.go
pkg/sdk/value/encryption/paseto/transformer.go

* Reduce allocation count in pasetov4 implementation
* Benchmark all primitives
* Expose rand.Reader to allow fixed nonce

feat(paseto): benchmarks and API changes.

---

test/fuzz/bundle/loader/fuzz_test.go
test/fuzz/template/fuzz_test.go

Migrate offline go-fuzz test to go 1.18 native fuzz tests.

feat(go): migrate offline fuzz tests to native go.

---

CHANGELOG.md
docs/onboarding/1-template-engine/2-functions.md
pkg/sdk/security/crypto/encoder.go
pkg/template/engine/funcs.go
pkg/template/engine/funcs_test.go

Register JWT template functions.

feat(template): JWT parser/verifier.

---

CHANGELOG.md
docs/onboarding/1-template-engine/2-functions.md
pkg/sdk/security/crypto/encoder.go
pkg/template/engine/funcs.go
samples/tlsa-dane-bind-zone/README.md
samples/tlsa-dane-bind-zone/template.yaml
samples/tlsa-dane-bind-zone/tlsa-homelab.zone

* Certificate handling template functions
- https://datatracker.ietf.org/doc/html/rfc6698

Feat template crypto tls dane compute

---

CHANGELOG.md
cmd/harp/loader_fips.go
cmd/harp/loader_nonfips.go
docs/onboarding/4-value-transformers/2-encryption.md
pkg/sdk/value/encryption/dae/builders.go
pkg/sdk/value/encryption/dae/helpers.go
pkg/sdk/value/encryption/dae/transformer.go
pkg/sdk/value/encryption/transformer_test.go

Add Deterministic Authenticated Encryption value transformers.
- https://en.wikipedia.org/wiki/Deterministic_encryption

feat(value): deterministic authenticated encryption.

---

CHANGELOG.md
cmd/harp/internal/cmd/transform_decrypt.go
cmd/harp/internal/cmd/transform_encrypt.go
docs/cmd/harp.md
docs/cmd/harp_completion.md
docs/cmd/harp_completion_bash.md
docs/cmd/harp_completion_fish.md
docs/cmd/harp_completion_powershell.md
docs/cmd/harp_completion_zsh.md
docs/cmd/harp_to_github-actions.md
docs/cmd/harp_transform_decrypt.md
docs/cmd/harp_transform_encrypt.md
docs/onboarding/4-value-transformers/2-encryption.md
pkg/sdk/value/encryption/aead/builders.go
pkg/sdk/value/encryption/aead/helpers.go
pkg/sdk/value/encryption/aead/transformer.go
pkg/sdk/value/encryption/context.go
pkg/sdk/value/encryption/dae/builders.go
pkg/sdk/value/encryption/dae/helpers.go
pkg/sdk/value/encryption/dae/transformer.go
pkg/sdk/value/encryption/transformer_test.go
pkg/tasks/bundle/decrypt_test.go
pkg/tasks/bundle/encrypt_test.go

* Support additional data for AEAD and DAE encryption
* Support `salt` for key derivation used in DAE encryption to diverge encryption keys from the same transformer key

feat(value): additional data support for AEAD/DAE transformers.

---

.github/dependabot.yaml
.github/workflows/github-release.yml
build/mage/docker/release.go

* Split cosign binary signature
* Checksum per artifact
* Disable UPX

chore(ci): artifact releaser

---

.gitignore
.goreleaser.yaml

* Test `goreleaser` as release builder to simplify the release process.

chore(ci): use goreleaser.

---

cmd/harp/internal/cmd/lint.go
docs/cmd/harp_lint.md
pkg/tasks/lint/validate.go

Autodetect schema for content validation based on file attributes (apiVersion / kind).

feat(lint): schema autodetection from content.

---

cmd/harp/internal/cmd/crate.go
cmd/harp/internal/cmd/crate_copy.go
cmd/harp/internal/cmd/crate_push.go
docs/cmd/harp_crate.md
docs/cmd/harp_crate_copy.md
pkg/crate/build.go
pkg/crate/oci.go
pkg/crate/pull.go
pkg/tasks/crate/copy.go
pkg/tasks/crate/push.go

feat(create): copy command.

---

.github/workflows/security.yml

[chore] Repo Maintenance

---

pkg/bundle/ruleset/bundle_test.go
pkg/sdk/value/encryption/transformer_test.go

Fix failing test for `ruleSet`.
Rel:
- https://github.com/elastic/harp/pull/271

[test] Update failing tests in ruleset

---

.github/workflows/codeql-analysis.yml
.github/workflows/go.yml
.github/workflows/releaser.yml
.github/workflows/security.yml

Closes https://github.com/elastic/harp/issues/286

ci: replace hardcoded go version with go.mod version

---

.github/workflows/releaser.yml

chore: update goreleaser command options

---

.goreleaser.yaml

build: update goreleaser configuration file to version 2

---

.github/workflows/releaser.yml

build: bump cyclonedx github action to v2

---

.github/workflows/releaser.yml

fix: update artifact names for github release workflow

---

.github/workflows/releaser.yml

build: update apple applicationID

---

.github/workflows/releaser.yml

```
/Users/runner/work/_temp/7d453f48-e105-4397-b451-53743a0acc45.sh: line 4: sha256sum: command not found
```

build: update release workflow for sha256 command

---

.github/workflows/releaser.yml

build: enable skipping of confirmation for cosign
