elastic/harp

README.md

* LGTM is now integrated into Github, so I decided to remove the badge.
* Added various OSS badges.

doc(readme): replace lgtm badge by oss statuses.

---

build/mage/docker/build.go
build/mage/docker/release.go
build/mage/docker/tools.go

Mage docker tasks fail on Linux due to `base64` arguments difference between OSX and Linux.
* Generated dockerfile is directly injected via a subprocess using stdin.

fix(ci): pass dockerfile directly to docker subprocess.

---

.golangci.yml
NOTICE.txt
docs/dependencies.asciidoc
go.mod
pkg/template/engine/funcs_test.go
pkg/template/engine/internal/codec/encoder.go
pkg/template/values/toml/toml.go

`github.com/BurntSushi/go-toml` is unmaintained.
* toml library migrated to `github.com/pelletier/go-toml`
* golangci check validated toml library usage
* golangci enforce valid license header

chore(go): migrate to github.com/pelletier/go-toml.

---

pkg/bundle/secret/packer.go
pkg/bundle/secret/packer_test.go
pkg/bundle/vault/internal/operation/exporter.go
pkg/bundle/vault/internal/operation/importer.go

Secret values are packed using ASN.1 (previously msgpack), this is stricter than msgpack. I want to enforce by design that secret KV must be sort of `map[string]string` in order to prevent subtree inside a secret value.
If a secret value is an object, it must be encoded as a string (using JSON encoding for example) before inserting it as secret. 
A cleaner error message is also produced in order to help the user to diagnose which secret path is responsible for the error raise.

fix(secret): wrap asn.1 encoding to detect version.

---

pkg/bundle/vault/internal/operation/exporter.go

Error wrapping was using wrong error instance.

fix(pack): error wrapping was using wrong error object.

---

cmd/harp-server/README.md
cmd/harp-server/go.mod
cmd/harp-server/go.sum
cmd/harp-server/internal/cmd/http.go
cmd/harp-server/internal/cmd/vault.go
cmd/harp-server/internal/config/config.go
cmd/harp-server/internal/dispatchers/vault/routes/api.go
cmd/harp-server/internal/dispatchers/vault/routes/helpers.go
cmd/harp-server/internal/dispatchers/vault/routes/kv.go
cmd/harp-server/internal/dispatchers/vault/routes/root.go
cmd/harp-server/internal/dispatchers/vault/routes/transit.go
cmd/harp-server/internal/dispatchers/vault/wire.go
cmd/harp-server/internal/dispatchers/vault/wire_gen.go

Expose transformers using a limited Vault Transit HTTP API.
* `[POST/PUT] /v1/transit/encrypt/:name`
* `[POST/PUT] /v1/transit/decrypt/:name`
Harp supports additional encryption algorithm not supported by Vault at the moment :
* `aes-256` match `aes256-gcm96` in Vault
* `fernet` and `secretbox (XSalsa20+Poly1305)` are not supported

feat(harp-server): Vault transit backend API for transformers.

---

README.md
build/mage/docker/build.go
build/mage/docker/release.go
build/mage/docker/tools.go
build/mage/golang/init.go
build/mage/golang/source.go
go.mod
go.sum
pkg/sdk/cmdutil/bug.go
pkg/sdk/cmdutil/plugin.go

- Update go toolchain constraint to [1.15.6, 1.15.7]
- Migrate `os/exec` package usage to `golang.org/x/sys/execabs`
- https://blog.golang.org/path-security
- https://groups.google.com/g/golang-announce/c/mperVMGa98w

Chore go update (1.15.7)

---

cmd/harp/internal/cmd/from_vault.go
cmd/harp/internal/cmd/to_vault.go
pkg/bundle/vault/internal/operation/exporter.go
pkg/bundle/vault/internal/operation/importer.go
pkg/bundle/vault/options.go
pkg/bundle/vault/pull.go
pkg/bundle/vault/push.go
pkg/tasks/from/vault.go
pkg/tasks/to/vault.go

Change `GOMAXPROCS` to `NumCpu +1` to prevent no CPU allocation due to detection problem in a docker container.

fix(go): use NumCpu in place of GOMAXPROCS.

---

cmd/harp/internal/cmd/from_dump.go
pkg/bundle/codec.go
pkg/bundle/codec_test.go
pkg/bundle/helpers.go
pkg/tasks/from/dump.go

`bundle dump` and `from dump` are using JSON encoded values to be able to update container version without the knowledge of internal encoding (ASN.1).

feat(json): export values using json.

---

pkg/bundle/vault/internal/operation/exporter.go
pkg/bundle/vault/internal/operation/importer.go
pkg/bundle/vault/push.go
pkg/tasks/from/vault.go
pkg/tasks/to/vault.go
pkg/vault/helpers.go

Vault error was masked by an invalid errorgroup usage.

fix(vault): don't hide vault error.

---

pkg/container/codec_test.go

`memguard` (software enclave) could raise an error during speed fuzz. Identity is a 32bytes long byte array but the test was unbounded to the desired identity size.
I suspect that fuzz could allocate a very big byte array that could crash the test.
```
12:06:32  #18 105.3 === Failed
12:06:32  #18 105.3 === FAIL: pkg/container Test_UnSeal_Fuzz (0.01s)
12:06:32  #18 105.3 panic: <memcall> could not acquire lock on 0x7f3e94b03000, limit reached? [Err: cannot allocate memory] [recovered]
12:06:32  #18 105.3 	panic: <memcall> could not acquire lock on 0x7f3e94b03000, limit reached? [Err: cannot allocate memory]
12:06:32  #18 105.3 
12:06:32  #18 105.3 goroutine 59 [running]:
12:06:32  #18 105.3 testing.tRunner.func1.1(0x86c3a0, 0xc00018db40)
12:06:32  #18 105.3 …
```

fix(fuzz): memguard random race condition during fuzz

---

pkg/container/codec_test.go

Fuzz tests with memguard randomly generate 1 issue. This is the second attempt to fix this test.
```
09:18:46  #18 98.46 === Failed
09:18:46  #18 98.46 === FAIL: pkg/container Test_UnSeal_Fuzz (0.01s)
09:18:46  #18 98.46 panic: <memcall> could not acquire lock on 0x7f94c851c000, limit reached? [Err: cannot allocate memory] [recovered]
09:18:46  #18 98.46 	panic: <memcall> could not acquire lock on 0x7f94c851c000, limit reached? [Err: cannot allocate memory]
09:18:46  #18 98.46 
09:18:46  #18 98.46 goroutine 6 [running]:
09:18:46  #18 98.46 testing.tRunner.func1.1(0x86c3a0, 0xc00011b010)
09:18:46  #18 98.46 	/usr/local/go/src/testing/testing.go:1072 +0x46a
09:18:46  #18 98.46 testing.tRunner.func1(0xc0001d3200)
09:18:46  #18 98.46 	/usr/local/go/src/testing/testing.go:1075 +0x636
09:18:46 …
```

fix(test): fix fuzz tests with memguard.

---

cmd/harp-server/internal/dispatchers/http/routes/backend.go
cmd/harp-server/internal/dispatchers/vault/routes/kv.go

`golang-ci` raised 2 errorlint in `harp-server`.

fix(lint): errorlint for harp-server.

---

pkg/bundle/vault/internal/operation/api.go
pkg/bundle/vault/internal/operation/exporter.go
pkg/bundle/vault/internal/operation/exporter_test.go
pkg/bundle/vault/internal/operation/importer.go
pkg/server/storage/backends/vault/engine.go
pkg/vault/kv/api.go
pkg/vault/kv/builder_test.go
pkg/vault/kv/secret_reader.go
pkg/vault/kv/secret_reader_test.go
pkg/vault/kv/v1_service.go
pkg/vault/kv/v1_service_test.go
pkg/vault/kv/v2_service.go
pkg/vault/kv/v2_service_test.go
pkg/vault/logical/api.go

* Add the ability to export a given secret version from Vault
* Export Vault KV metadata as annotations and set the `packages[].secrets.version` value
> Using version on a fuzzy path matcher wil not work and return an `empty` secret set.
```
$ harp from vault --path app/production/customer1/ece/v1.0.0/userconsole/http/session | harp bundle dump | jq
{
"packages": [
{
"annotations": {
"www.vaultproject.io/kv/metadata": "{\"created_time\":\"2021-02-05T10:58:25.353833Z\",\"deletion_time\":\"\",\"destroyed\":false,\"version\":2}",
"www.vaultproject.io/kv/v2/metadata#createdTime": "2021-02-05T10:58:25.353833Z",
"www.vaultproject.io/kv/v2/metadata#version": "2"
},
"name": "app/production/customer1/ece/v1.0.0/userconsole/http/session",
"secrets": {
"version": 2,
"data": [
.. REDACTED ..
]
}
}
], …
```

Feat vault version puller

---

pkg/bundle/vault/internal/operation/exporter.go
pkg/bundle/vault/internal/operation/exporter_test.go
pkg/vault/kv/api.go
pkg/vault/kv/v1_service.go
pkg/vault/kv/v2_service.go

Fix a codeql finding for invalid integer parsing.

fix(codeql): invalid integer parsing.

---

README.md
build/mage/golang/init.go

Update go to `1.15.8`
- https://github.com/golang/go/issues?q=milestone%3AGo1.15.8+label%3ACherryPickApproved

chore(go): 1.15.8

---

pkg/bundle/patch/package.go
pkg/bundle/patch/package_test.go
test/fixtures/patch/valid/path-cleaner.yaml

Patch application raised an error when package names are duplicated. By design, package names should be unique but during pipeline development, this is an encounterable situation. 
Thanks to @dgolja

fix(bundle): package concurrent iteration problem with duplicate names.

---

pkg/sdk/value/encryption/aead/helpers.go

Add a missing boundary check to prevent overflow.

fix(sec): missing boundary check.

---

.github/workflows/pr.yml
.golangci.yml
pkg/sdk/security/crypto/asymmetric.go
pkg/vault/logical/logical.mock.go
tools/go.mod

`golangci-lint` released the `v1.37.0` version to support go 1.16.

chore(tools): update to golangci-lint v1.37.0

---

README.md
build/mage/golang/init.go

Update go to `1.16.4`
- https://github.com/golang/go/issues?q=milestone%3AGo1.16.4+label%3ACherryPickApproved
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-31525

chore(go): update to 1.16.4

---

pkg/bundle/patch/executor.go

Bug discovered by fuzz.
PBundlePatch rule with nil package declaration makes patch panic.

fix(fuzz): patch rule with nil package.

---

cmd/harp/internal/cmd/template.go

Template engine can load secret via `SecretLoaders`. You can load secret from vault or from a secret container. The secret container was using the old bundle loader before the separated container concept introduction.

fix(template): use container reader.

---

CHANGELOG.md
README.md
build/mage/docker/build.go
build/mage/docker/release.go
build/mage/docker/tools.go
build/mage/golang/init.go
build/mage/golang/source.go
cmd/harp/internal/cmd/plugin_list.go
cmd/harp/internal/cmd/template.go
cmd/harp/internal/cmd/transform_encryption.go
pkg/bundle/codec.go
pkg/bundle/patch/reader.go
pkg/bundle/ruleset/bundle.go
pkg/bundle/ruleset/linter/reader.go
pkg/bundle/template/reader.go
pkg/bundle/vfs/fs_test.go
pkg/container/codec.go
pkg/kv/api.go
pkg/sdk/cmdutil/bug.go
pkg/sdk/cmdutil/plugin.go
pkg/sdk/convert/yaml.go
pkg/sdk/security/crypto/encoder.go
pkg/sdk/tlsconfig/config.go
pkg/template/cmdutil/values.go
pkg/template/engine/values.go
pkg/template/values/hocon/hocon.go
test/cmd/suite_test.go
tools/go.mod

* Update go toolchain to 1.17.3
* Update golangci-lint to 1.43.0
- https://groups.google.com/g/golang-announce/c/0fM21h43arc/m/a2Hu_dWRAAAJ
- https://github.com/golang/go/issues/48085

chore(go): update to 1.17.3.

---

CHANGELOG.md
README.md
pkg/sdk/security/crypto/paseto/v4/helpers.go
pkg/sdk/security/crypto/paseto/v4/helpers_test.go
pkg/sdk/value/encryption/paseto/transformer.go
shell.nix

PASETOv4 implementation embedded the transformer package. To make primitives more useable, I moved the PASETOv4 primitives to the security SDK.

feat(crypto): move pasetov4 to security sdk.

---

README.md
build/mage/golang/init.go
build/mage/golang/lint.go

chore(go): enable go1.18.

---

CHANGELOG.md
tools/go.mod
tools/go.sum

`golangci-lint` imports a dependency `go-header` from `github.com/denis-tingajkin/go-header` which is not existing any more and redirect the dependency to `github.com/denis-tingaikin/go-header` (j vs i).
The `denis-tingajkin` could be claimed and used to publish a `fake`go-header which will be used to pollute the tool.
- https://github.com/golangci/golangci-lint/blob/master/go.mod#L23

chore(go): fix possible dependency spoofing.

---

pkg/bundle/vault/internal/operation/exporter.go

Fix an issue where the returned custom metadata could be nil, and raise a warning.

fix(vault): custom metadata could be nil.

---

pkg/bundle/pipeline/builder.go
pkg/bundle/pipeline/executor.go

Allow `Bundle` pipeline executor to use external reader/writer instances.

feat(pipeline): allow reader/writer customization.

---

CHANGELOG.md
cmd/harp/internal/cmd/from_hcl.go
docs/cmd/harp_from.md
docs/cmd/harp_from_hcl.md
go.mod
go.sum
pkg/bundle/builders.go
pkg/bundle/hcl/config.go
pkg/bundle/hcl/parser.go
pkg/bundle/hcl/parser_test.go
pkg/bundle/hcl/testdata/basic.hcl
pkg/bundle/hcl/testdata/basic.hcl.golden
pkg/bundle/hcl/testdata/complex.hcl
pkg/bundle/hcl/testdata/complex.hcl.golden
pkg/tasks/from/hcl.go

Create Bundle from a HCLv2 descriptor.
```hcl
annotations = {
"secrets.elastic.co/leakSeverity" = "moderate"
}
package "platform/security/databases/postgresql" {
description = "Administrative access for database management."
annotations = {
"infosec.elastic.co/v1/SecretManagement#rotationPeriod" = "90"
"infosec.elastic.co/v1/SecretManagement#generationDate" = "{{ now | isodate }}"
}
secrets = {
"USER" = "admin-{{ randAlpha 8 }}"
"PASSWORD" = "{{ strongPassword | b64enc }}"
}
}
```
```sh
$ harp template --in bundle.hcl | harp from hcl 
```

feat(bundle): HCL bundle descriptor.

---

pkg/bundle/hcl/parser_test.go
pkg/bundle/hcl/testdata/complex.hcl

Apply endline character normalization on golden tests

fix(test): disable golden tests due to map order stability.

---

.github/workflows/github-release.yml
build/artifact/gon.hcl

Add MacOS binaries code signing and notarization to release process.

chore(ci): macos binaries code signing and notarization.

---

api/jsonschema/harp.bundle.v1/RuleSet.json
pkg/sdk/convert/yaml.go
pkg/sdk/convert/yaml_test.go
pkg/tasks/bundle/diff.go
pkg/tasks/to/ruleset.go

* Make `owner` not mandatory in `RuleSet`JSON Schema
* Add a Protobuf to YAML conversion helper who uses protojson as an intermediary encoder to get the right protobuf object annotations
* Apply fix to `RuleSet`and `Patch` tasks which were producing an `api_version` property instead of the expected `apiVersion` format
```
$ harp from object --in ~/demo/219/input.json --out - | harp to ruleset --in -
apiVersion: harp.elastic.co/v1
kind: RuleSet
meta:
description: Generated from bundle content
name: qBiWpFkYKhkuBUXyIxxA1fSWCDXV8jHBJkgArt7D2dwqZ4mn_k7s2JbomfjzB_tNEI9CJXJ1n5cflhb96ao3lA
spec:
rules:
- constraints:
- p.has_secret("bar")
name: LINT-qBiWpF-1
path: secrets/foo/test
```
fix https://github.com/elastic/harp/issues/219

Fix yaml serialization from pb

---

pkg/bundle/ruleset/bundle.go
pkg/bundle/ruleset/bundle_test.go
pkg/bundle/ruleset/package.go
pkg/sdk/value/encryption/transformer_test.go
pkg/tasks/bundle/decrypt_test.go
pkg/tasks/container/recover_test.go

Adds support for generation of additional metadata when using the bundle as the source for a ruleSet.
When validating bundles, this update include all annotations and labels in the RuleSet.
```yaml
apiVersion: harp.elastic.co/v1
kind: BundleTemplate
meta:
name: "example"
owner: test@example.com
description: "exmaple bundle"
spec:
selector:
quality: "production"
platform: "testPlatform"
product: "testProduct"
version: "v1.0.0"
namespaces:
platform:
- region: "us-east-1"
components:
- name: "testComponent"
secrets:
- suffix: "testCredentials"
description: "test credentials"
labels:
vendor: "true"
annotations:
infosec.elastic.co/rotationPeriod: "90d"
template: |-
{
"foo": "{{ noSymbolPassword }}"
}
```
The expected output should include all defined annotations and labels for the secret.
``` …
```

[RuleSet] add support for annotations and labels

---

.github/workflows/go.yml
.github/workflows/releaser.yml
.github/workflows/security.yml

Pinning action to a full length commit SHA [see](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)

pinning github actions

---

pkg/bundle/fs/api.go
pkg/bundle/fs/directory.go
pkg/bundle/fs/direntry.go
pkg/bundle/fs/file.go
pkg/bundle/fs/file_info.go
pkg/bundle/fs/root.go
pkg/bundle/fs/root_test.go
test/fuzz/bundle/loader/fuzz_test.go
test/fuzz/template/fuzz_test.go

go.mod requires go 1.23, remove old go version build tag

refactor: remove unnecessary go build tags

---

.github/dependabot.yaml

move schedule interval to weekly
should reduce dependabot PR noise

ci: group github-action updates

---

.github/workflows/releaser.yml

```
2025-04-30T19:01:25.0544610Z 1 error occurred:
2025-04-30T19:01:25.0545060Z 	* 1 error occurred:
2025-04-30T19:01:25.0546160Z 	* Notarization of MacOS applications using altool has been decommissioned. Please use notarytool. See: https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool (-1031)
```

build: disable apple notarization for release workflow
